steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: ['-c', 'git clone https://github.com/WiswaPillai/test.git']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'test'
    args: ['install']

  - name: 'ubuntu'
    secretEnv: ['aws-ec2-private-key']
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get update && apt-get install -y openssh-client

        echo "Writing private key to file..."
        cat > ec2_key.pem <<EOF
        $aws-ec2-private-key
        EOF
        chmod 600 ec2_key.pem

        # Copy project files to EC2'
        echo 'Copying files to EC2 instance...'
        scp -i ec2_key.pem -o StrictHostKeyChecking=no -r test gcpuser@ec2-3-111-188-92.ap-south-1.compute.amazonaws.com:/home/gcpuser/app
        echo 'Files copied to EC2 instance.'

        echo 'Running deploy commands on EC2...'
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no gcpuser@ec2-3-111-188-92.ap-south-1.compute.amazonaws.com <<EOF
          cd /home/gcpuser/app
          npm install
          echo "Deployment completed successfully."
        EOF

availableSecrets:
  secretManager:
    - versionName: projects/common-tools-265603/secrets/aws-ec2-private-key/versions/latest
      env: aws-ec2-private-key

options:
  logging: CLOUD_LOGGING_ONLY
